export const en = {
  "opencodez.prompts.title": "System prompts",
  "opencodez.prompts.manage": "Manage prompts…",
  "opencodez.prompts.actions": "More actions",
  "opencodez.prompts.auto": "Automatic",
  "opencodez.prompts.none": "No core prompt",
  "opencodez.prompts.all": "All",
  "opencodez.prompts.builtin": "Built-in",
  "opencodez.prompts.mine": "My prompts",
  "opencodez.prompts.file": "Markdown file",
  "opencodez.prompts.deleted": "Deleted",
  "opencodez.prompts.create": "Create prompt",
  "opencodez.prompts.copy": "Create from this",
  "opencodez.prompts.name": "Name",
  "opencodez.prompts.description": "Description",
  "opencodez.prompts.text": "Instructions",
  "opencodez.prompts.placeholder": "Write the agent’s core instructions…",
  "opencodez.prompts.coreHint": "Environment, project and tool instructions are added separately.",
  "opencodez.prompts.save": "Save",
  "opencodez.prompts.saved": "Saved · applies next turn",
  "opencodez.prompts.unsaved": "Unsaved changes",
  "opencodez.prompts.discard": "Discard changes",
  "opencodez.prompts.back": "Back to prompts",
  "opencodez.prompts.use": "Use in this chat",
  "opencodez.prompts.saveUse": "Save and use in this chat",
  "opencodez.prompts.useShort": "Use in chat",
  "opencodez.prompts.saveUseShort": "Save & use",
  "opencodez.prompts.properties": "Prompt details",
  "opencodez.prompts.thisPrompt": "This prompt",
  "opencodez.prompts.resetShort": "Built-in",
  "opencodez.prompts.inheritShort": "Inherit",
  "opencodez.prompts.families": "Families",
  "opencodez.prompts.exception": "Exception",
  "opencodez.prompts.applyShort": "Apply",
  "opencodez.prompts.savedShort": "Saved",
  "opencodez.prompts.autoShort": "Auto",
  "opencodez.prompts.backEditor": "Back to prompt",
  "opencodez.prompts.unassignedShort": "Not assigned",
  "opencodez.prompts.defaults": "Default for",
  "opencodez.prompts.assign": "Edit assignments",
  "opencodez.prompts.apply": "Apply assignments",
  "opencodez.prompts.inherit": "Remove rule",
  "opencodez.prompts.reset": "Use built-in default",
  "opencodez.prompts.family": "Family",
  "opencodez.prompts.model": "Model",
  "opencodez.prompts.models": "Models",
  "opencodez.prompts.coverage": "Models in this family",
  "opencodez.prompts.exceptions": "Exact personal rules stay active",
  "opencodez.prompts.replaces": "Replaces",
  "opencodez.prompts.current": "Current",
  "opencodez.prompts.otherDefaults": "Other defaults",
  "opencodez.prompts.unassigned": "No personal assignment",
  "opencodez.prompts.global": "All models",
  "opencodez.prompts.fallback": "Models without an assignment",
  "opencodez.prompts.globalHint": "An all-model rule overrides individual assignments.",
  "opencodez.prompts.removeGlobal": "Remove all-model rule",
  "opencodez.prompts.globalWillReset": "Applying these assignments will disable the all-model rule.",
  "opencodez.prompts.delete": "Delete prompt",
  "opencodez.prompts.deleteHint":
    "Remove this prompt and its personal assignments? Existing chats keep access to its text.",
  "opencodez.prompts.restore": "Restore",
  "opencodez.prompts.deletedHint": "Deleted from the library. Existing chats can still use this prompt.",
  "opencodez.prompts.sourceUpdated": "The built-in source was updated",
  "opencodez.prompts.viewSource": "View source",
  "opencodez.prompts.import": "Import",
  "opencodez.prompts.export": "Export",
  "opencodez.prompts.exportAll": "Export my prompts",
  "opencodez.prompts.includeRules": "Include model assignments",
  "opencodez.prompts.markdown": "Markdown text",
  "opencodez.prompts.bundle": "OpenCodez bundle",
  "opencodez.prompts.importPreview": "Review import",
  "opencodez.prompts.keep": "Keep current",
  "opencodez.prompts.replace": "Replace with incoming",
  "opencodez.prompts.importCopy": "Import a copy",
  "opencodez.prompts.new": "New",
  "opencodez.prompts.same": "Already present",
  "opencodez.prompts.changed": "Different text",
  "opencodez.prompts.importRules": "Apply included assignments",
  "opencodez.prompts.importRulesHint": "Review replacements before applying assignments.",
  "opencodez.prompts.importApply": "Import selected prompts",
  "opencodez.prompts.conflict": "This item changed elsewhere. Your draft is preserved. Refresh or save a copy.",
  "opencodez.prompts.refresh": "Refresh",
  "opencodez.prompts.error": "Could not save. Your draft is preserved.",
  "opencodez.prompts.invalidFile": "Choose a Markdown file or a valid OpenCodez prompt bundle.",
  "opencodez.prompts.empty": "Choose a prompt or create your own.",
  "opencodez.prompts.reasoning": "Default reasoning",
  "opencodez.prompts.reasoningHint": "Used automatically. Manual choices in a chat stay active.",
  "opencodez.prompts.providerDefault": "Model default",
  "opencodez.prompts.saveReasoning": "Save reasoning defaults",
  "opencodez.prompts.server": "Server",
  "opencodez.prompts.cancel": "Cancel",
  "opencodez.prompts.copiedName": "Copy",
}

export const ru: typeof en = {
  "opencodez.prompts.title": "Системные промпты",
  "opencodez.prompts.manage": "Управлять промптами…",
  "opencodez.prompts.actions": "Другие действия",
  "opencodez.prompts.auto": "Автоматически",
  "opencodez.prompts.none": "Без содержательного промпта",
  "opencodez.prompts.all": "Все",
  "opencodez.prompts.builtin": "Встроенные",
  "opencodez.prompts.mine": "Мои промпты",
  "opencodez.prompts.file": "Markdown-файл",
  "opencodez.prompts.deleted": "Удалённые",
  "opencodez.prompts.create": "Создать промпт",
  "opencodez.prompts.copy": "Создать на основе",
  "opencodez.prompts.name": "Название",
  "opencodez.prompts.description": "Описание",
  "opencodez.prompts.text": "Инструкции",
  "opencodez.prompts.placeholder": "Напишите основные инструкции для агента…",
  "opencodez.prompts.coreHint": "Окружение, инструкции проекта и инструментов добавляются отдельно.",
  "opencodez.prompts.save": "Сохранить",
  "opencodez.prompts.saved": "Сохранено · со следующего хода",
  "opencodez.prompts.unsaved": "Есть несохранённые изменения",
  "opencodez.prompts.discard": "Отбросить изменения",
  "opencodez.prompts.back": "К списку промптов",
  "opencodez.prompts.use": "Использовать в этом чате",
  "opencodez.prompts.saveUse": "Сохранить и использовать в чате",
  "opencodez.prompts.useShort": "Выбрать в чате",
  "opencodez.prompts.saveUseShort": "Сохранить и выбрать",
  "opencodez.prompts.properties": "Сведения о промпте",
  "opencodez.prompts.thisPrompt": "Этот промпт",
  "opencodez.prompts.resetShort": "Встроенный",
  "opencodez.prompts.inheritShort": "Наследовать",
  "opencodez.prompts.families": "Семейства",
  "opencodez.prompts.exception": "Исключение",
  "opencodez.prompts.applyShort": "Применить",
  "opencodez.prompts.savedShort": "Сохранено",
  "opencodez.prompts.autoShort": "Авто",
  "opencodez.prompts.backEditor": "К промпту",
  "opencodez.prompts.unassignedShort": "Нет назначений",
  "opencodez.prompts.defaults": "По умолчанию для",
  "opencodez.prompts.assign": "Изменить назначения",
  "opencodez.prompts.apply": "Применить назначения",
  "opencodez.prompts.inherit": "Снять правило",
  "opencodez.prompts.reset": "Вернуть встроенное",
  "opencodez.prompts.family": "Семейство",
  "opencodez.prompts.model": "Модель",
  "opencodez.prompts.models": "Модели",
  "opencodez.prompts.coverage": "Модели этого семейства",
  "opencodez.prompts.exceptions": "Точные личные правила сохраняются",
  "opencodez.prompts.replaces": "Заменит",
  "opencodez.prompts.current": "Сейчас",
  "opencodez.prompts.otherDefaults": "Общие назначения",
  "opencodez.prompts.unassigned": "Личного назначения нет",
  "opencodez.prompts.global": "Все модели",
  "opencodez.prompts.fallback": "Модели без назначения",
  "opencodez.prompts.globalHint": "Общее правило перекрывает назначения отдельным моделям.",
  "opencodez.prompts.removeGlobal": "Снять общее правило",
  "opencodez.prompts.globalWillReset": "При применении этих назначений общее правило будет отключено.",
  "opencodez.prompts.delete": "Удалить промпт",
  "opencodez.prompts.deleteHint": "Удалить промпт и его личные назначения? Существующие чаты сохранят доступ к тексту.",
  "opencodez.prompts.restore": "Восстановить",
  "opencodez.prompts.deletedHint": "Удалён из библиотеки. Существующие чаты могут продолжать его использовать.",
  "opencodez.prompts.sourceUpdated": "Встроенный исходник обновился",
  "opencodez.prompts.viewSource": "Посмотреть исходник",
  "opencodez.prompts.import": "Импорт",
  "opencodez.prompts.export": "Экспорт",
  "opencodez.prompts.exportAll": "Экспортировать мои промпты",
  "opencodez.prompts.includeRules": "Включить назначения моделям",
  "opencodez.prompts.markdown": "Текст Markdown",
  "opencodez.prompts.bundle": "Набор OpenCodez",
  "opencodez.prompts.importPreview": "Проверка импорта",
  "opencodez.prompts.keep": "Оставить текущий",
  "opencodez.prompts.replace": "Заменить входящим",
  "opencodez.prompts.importCopy": "Импортировать копию",
  "opencodez.prompts.new": "Новый",
  "opencodez.prompts.same": "Уже есть",
  "opencodez.prompts.changed": "Другой текст",
  "opencodez.prompts.importRules": "Применить назначения из набора",
  "opencodez.prompts.importRulesHint": "Перед применением проверьте замены назначений.",
  "opencodez.prompts.importApply": "Импортировать выбранное",
  "opencodez.prompts.conflict":
    "Объект изменился в другом окне. Черновик сохранён. Обновите данные или сохраните копию.",
  "opencodez.prompts.refresh": "Обновить",
  "opencodez.prompts.error": "Не удалось сохранить. Черновик остаётся в редакторе.",
  "opencodez.prompts.invalidFile": "Выберите Markdown-файл или корректный набор промптов OpenCodez.",
  "opencodez.prompts.empty": "Выберите промпт или создайте свой.",
  "opencodez.prompts.reasoning": "Ризонинг по умолчанию",
  "opencodez.prompts.reasoningHint": "Для автоматического выбора. Ручной выбор в чате сохраняется.",
  "opencodez.prompts.providerDefault": "По умолчанию у модели",
  "opencodez.prompts.saveReasoning": "Сохранить настройки ризонинга",
  "opencodez.prompts.server": "Сервер",
  "opencodez.prompts.cancel": "Отмена",
  "opencodez.prompts.copiedName": "Копия",
}
